### ISSUE TITLE
error: '-mgeneral-regs-only' is incompatible with floating-point code

### ISSUE THREAD

**Issue by LZY-SPCA** [Joshua-Riek/linux-rockchip#25]
![image](https://github.com/user-attachments/assets/021d2220-5a3c-4d5a-93af-45562b5c0d75)

I use ubuntu22.04 in docker desktop.
uname -a:
Linux 43cf4c604a9c 6.6.36.3-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Sat Jun 29 07:01:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

cross_compiler:
gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu

**Comment by Joshua-Riek** [comment]
How are you compiling the kernel? What branch?

**Comment by LZY-SPCA** [comment]
I replaced the kernel in tspi SDK and used the command `./build.sh kernel`. The branch is 5.10.160-34.

**Comment by LZY-SPCA** [comment]
Did you change the branch and repository? It looks different.

**Comment by Joshua-Riek** [comment]
I re worked both the rockchip 5.10 and 6.1 kernels to follow upstream Ubuntu guidelines. 

I'm fully aware this causes confusion as the kernel methodology from Ubuntu is not documented well at all, but it's necessary so I can easily maintain multiple kernels and devices.

**Comment by LZY-SPCA** [comment]
Do you have any ideas about my errors?

**Comment by Joshua-Riek** [comment]
I have not encountered the error, so I can't give a solution. But try to Google the error.

**Comment by LZY-SPCA** [comment]
Sorry I forgot to reply.Remove the -mgeneral-regs-only flag located in arch/arm64/Makefile could solve the problem
