### ISSUE TITLE
pacman 7.0 requires the kernel supports landlock, linux-aarch64-rockchip-bsp6.1-joshua-git 6.1.75

### ISSUE THREAD

**Issue by endeavouros-arm** [Joshua-Riek/linux-rockchip#31]
Archlinux pacman 7.0 has added support for downloading packages as a separate user with dropped privileges.
https://archlinux.org/news/manual-intervention-for-pacman-700-and-local-repositories-required/

This requires that the kernel supports landlock. Running with linux-aarch64-rockchip-bsp6.1-joshua-git 6.1.75 yields the following error.

error: restricting filesystem access failed because landlock is not supported by the kernel!

This doesn't stop pacman from updating, it just isn't utilizing the new security feature, which would be nice to have available.

I don't know if this does you any good, but adding the following to the PKGBUILD config file, added landlock to kernels I compile for Odroid N2 and Pinebook Pro.

change from
CONFIG_SECURITY_LANDLOCK is not set
to
CONFIG_SECURITY_LANDLOCK=y

and from
CONFIG_LSM="yama,loadpin,safesetid,integrity,selinux,smack,tomoyo,apparmor"
to
CONFIG_LSM="yama,loadpin,safesetid,integrity,selinux,smack,tomoyo,apparmor,landlock"

For me, this added landlock to the kernel and the new feature works.
In an existing install, pacman will generate some .pacnew files that need to be dealt with, and a new user 'alpm' is created for support for downloading packages as a separate user with dropped privileges.

Thank you for the work on the linux-aarch64-rockchip-bsp6.1-joshua-git 6.1.75 kernel

**Comment by Joshua-Riek** [comment]
Was this change tested with this kernel? I'm not able to test for a while and since this kernel is very messy there is a chance enabling this driver may not work.

**Comment by endeavouros-arm** [comment]
No Sir.  This was tested on a very vanilla kernel I compile for aarch64.
This is not a big deal, so if it turns into a lot of headaches, it is not necessary to do this.

**Comment by kwankiu** [comment]
@endeavouros-arm,

would you consider asking Armbian?

https://github.com/armbian/build/blob/main/config/kernel/linux-rk35xx-vendor.config

**Comment by Joshua-Riek** [comment]
I will be direct; I prefer people send pull requests instead of asking me to make changes and do testing on their behalf. I'm already tired and it will eventually be impossible to respond to requests like this if everyone does the same.

**Comment by Joshua-Riek** [comment]
Yeah, I'm going to close this, I don't have the time to add and test the feature you require. 

You're welcome to test it out yourself and send a pull request.
